title: Deep C
description: >-
  A site to assist experienced programmers on their journey towards
  a deeper understanding of the C programmning language.
baseurl: ""
url: "https://deep-c.com"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - home.md
  - resources.md
  - about.md
