title: Deep C
description: >-
  A webpage dedicated to stuff related to developing a deep understanding of
  the C programmning language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deep-c.com"

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - home.markdown
  - about.markdown
